version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: last_name
        tests:
          - adv_not_null:
              column_to_exclude_on: customer_id
      - name: email
        tests:
          - adv_unique:
              column_to_exclude_on: customer_id

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: placed_by
        tests:
          - adv_not_null:
              event_timestamp_column_name: order_date
              number_of_days_to_check: 365

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']
          - adv_not_null:
              threshold_type: relative
              threshold_value: 5
